services:
  - type: web
    name: telegram-bingo
    runtime: node
    buildCommand: echo 'No build step required'
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: UPSTASH_REDIS_REST_URL
        value: https://absolute-feline-20781.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: AVEtAAIncDJiNGU4ZTQ3YjBiZWI0ZmI5YTZmNTE1ZjdiNTk5OWUxZHAyMjA3ODE
